### ISSUE TITLE
create deb file not install ,given error.

### ISSUE THREAD

**Issue by yeasin6152** [termux/termux-create-package#12]
When i make deb file with manifest.jeson file. This tool create perfectly deb file but when i testing deb file it given error. 

dpkg-deb (subprocess): decompressing archive member: lzma write error: Broken pipe
dpkg-deb (subprocess): cannot copy archive member from 'o.deb' to decompressor pipe: fail
d to write (Broken pipe)
dpkg-deb: error: subprocess <decompress> returned error exit status 2
Errors were encountered while processing:
 o.deb

**Comment by Grimler91** [comment]
Which OS are you using? What's the output of `tar --version`?

**Comment by yeasin6152** [comment]
Thanks to reply, my os is aarch64 and tar version is tar (busybox) 1.29.3.

**Comment by yeasin6152** [comment]
I install tar
tar --version >>(   tar (GNU tar) 1.30
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <
https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.ermux-create-package)

termux-create-package will create deb file without error....

But same error when i install it for testing . I give you a log >.


termux-create-package manifest.json
Building openjdk_10_jdk_bin_10.2018.03.20.1_aarch64.deb
$ ls
bin_1
manifest-make
manifest.json
openjdk
openjdk_10_jdk_bin_10.2018.03.20.1_aarch64.deb
sort_1.txt
temp.txt
$ dpkg -i openjdk_10_jdk_bin_10.2018.03.20.1_aarch64.deb
(Reading database ... 1563 files and directories currently installed.)
Preparing to unpack openjdk_10_jdk_bin_10.2018.03.20.1_aarch64.deb ...
Unpacking openjdk_10_jdk_bin (10.2018.03.20.1) ...
dpkg: error processing archive
openjdk_10_jdk_bin_10.2018.03.20.1_aarch64.deb (--install):
 unable to create
'/data/data/com.termux/files/usr/lib/jvm/openjdk/lib/security/cacerts.dpkg-new'
(while processing
'data/data/com.termux/files/usr/lib/jvm/openjdk/lib/security/cacerts'): No
such file or directory
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 openjdk_10_jdk_bin_10.2018.03.20.1_aarch64.deb
$
$ mc

$ ls
bin_1
manifest-make
manifest.json
openjdk
openjdk_10_jdk_bin_10.2018.03.20.1_aarch64.deb
sort_1.txt
temp.txt
$ mkdir nn
$ dpkg -x openjdk_10_jdk_bin_10.2018.03.20.1_aarch64.deb nn
$ find nn -type f
nn/data/data/com.termux/files/usr/lib/jvm/openjdk/lib/security/cacerts
nn/data/data/com.termux/files/usr/lib/jvm/openjdk/lib/security/blacklisted.certs
nn/data/data/com.termux/files/usr/lib/jvm/openjdk/lib/security/default.policy
nn/data/data/com.termux/files/usr/lib/jvm/openjdk/lib/libawt.so
nn/data/data/com.termux/files/usr/lib/jvm/openjdk/lib/libfontmanager.so
nn/data/data/com.termux/files/usr/lib/jvm/openjdk/lib/tzdb.dat


(continue).....

If i delete cacerts file then it will show same error with other file.

Please solve for me..... thank you.

**Comment by Grimler91** [comment]
Could you provide the faulty .deb file?

**Comment by yeasin6152** [comment]
I think my deb is not faulty because i make other deb file and when i
testing my deb file it give same error ----


dpkg -i apktool_2018.03.20.1_aarch64.deb
(Reading database ... 1557 files and directories currently installed.)
Preparing to unpack apktool_2018.03.20.1_aarch64.deb ...
Unpacking apktool (2018.03.20.1) ...
dpkg: error processing archive apktool_2018.03.20.1_aarch64.deb (--install):
 unable to create
'/data/data/com.termux/files/usr/lib/apktool/7z.sh.dpkg-new' (while
processing 'data/data/com.termux/files/usr/lib/apktool/7z.sh'): No such
file or directory
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 apktool_2018.03.20.1_aarch64.deb

I think it is problem have termux-create-package or tar tools or xz-utils .
But when i trying to build and install hello.word in your github example it
works done.
plz solve this and many many thanks to reply...

**Comment by xeffyr** [comment]
> I think it is problem have
> or tar tools or xz-utils

No problem with **tar** or **xz-utils**. I guess that you have problem with manifest.json as I used **termux-create-package** to create deb files and they installed without error.

Can you post contents of your manifest.json file ?

**Comment by yeasin6152** [comment]
Ok sir , i give you my Deb file and manifest.jeson file. Please download
and extrect it..... thanks.
https://mega.nz/#!PXwBEYRC!qgXEwZNJxCEFbp5y7HW_mhAzCJLgLI5qdufTuZjF6qA

**Comment by xeffyr** [comment]
@yeasin6152 Perhaps there problem with **termux-create-package** - there is something wrong with tar archive generation.

I suggest you to rebuild your deb file in this way:
```
dpkg-deb -R apktool_2018.03.20.1_aarch64.deb unpacked
dpkg-deb -b unpacked apktool_2018.03.20.1_aarch64_fixed.deb
```

You will get file `apktool_2018.03.20.1_aarch64_fixed.deb` which can be installed with `dpkg -i`.

**Comment by xeffyr** [comment]
@yeasin6152 Fixed deb file: https://transfer.sh/vXoWZ/apktool_2018.03.20.1_aarch64.deb

**Comment by yeasin6152** [comment]
@xeffyr sir, at this time apktool won't work on Android 8 or later but developer trying to finding the way to make it. Jest a few time need to wait.. and thanks to give solution.
And last problem is I make java Deb file and it install successful but when I type Java in terminal it show Java permission denied. After given permission it works. Why installed Deb file need to permission . And how to solve it. Plz help..
