### ISSUE TITLE
How To Add Custom Command On Deb Packages

### ISSUE THREAD

**Issue by RootSh311** [termux/termux-create-package#16]
How To Add Custom Commands On deb packages. If I Need To Install Some Pip requirement or ruby-gem. You Know Some Times Python Based Tools Need PIP requirements. I Hope You Can Understand

**Comment by Grimler91** [comment]
You can put the commands in a [postinst script](https://www.debian.org/doc/manuals/debian-faq/ch-pkg_basics.en.html#s-maintscripts), it is then run after the installation. See for example [nzbget](https://github.com/termux/termux-packages/blob/b7a5b4777505fb7d82b71d0d032dc9b5286e599e/packages/nzbget/build.sh#L12) for an example where it is used.

termux-create-package doesn't support postinst and similar scripts though, so you need to either add it manually or improve termux-create-package so it can handle such scripts

**Comment by RootSh311** [comment]
How Do I Add Postinst script to my .Deb packages. I am new at this can you help
