### ISSUE TITLE
How To Add postint Script To .deb packages

### ISSUE THREAD

**Issue by RootSh311** [termux/termux-create-package#17]
I Have Created A .deb package. And It Requied Some pip package so i have create a postinit but i don't know where to put the postinit on manifest.json and the directory. Xeffry Please Help Me. Don't Close This Issuse Until I Get The Answer. If You Close This Issuse Without Answer Then I Will Open A New One

**Comment by xeffyr** [comment]
termux-create-package does not support pre-/post-install scripts.

**Comment by RootSh311** [comment]
Okkk. Thank You For Your Time
