### ISSUE TITLE
[Feature Request] Support for manifest suggests and recommends fields as well as debscripts

### ISSUE THREAD

**Issue by Yuriusu** [termux/termux-create-package#23]
This is just a notice. I've already submitted a pr [#22](https://github.com/termux/termux-create-package/pull/22).

Summary of the request:

1. Add an optional manifest _suggests_ and _recommends_ fields (see `TERMUX_PKG_RECOMMENDS` and `TERMUX_PKG_SUGGESTS` in [package control fields](https://github.com/termux/termux-packages/wiki/Creating-new-package#table-of-available-package-control-fields)).
2. Add an optional package maintainer scripts, or _debscripts_ (see [maintainer scripts](https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html) and `termux_step_create_debscripts` in [build steps override](https://github.com/termux/termux-packages/wiki/Creating-new-package#table-of-available-build-step-overrides))

**Comment by meiuwa** [comment]
@xeffyr What do you think?

**Comment by Yuriusu** [comment]
@xeffyr What do you think?
