### ISSUE TITLE
Add function to run scripts/commands during installation 

### ISSUE THREAD

**Issue by Yisus7u7** [termux/termux-create-package#27]
Hello, I use termux-create-package and termux-apt-repo on my cell phone, everything is excellent, very versatile and easy to use, but I would like you to add the function of running a script during installation, to install things like example, python dependencies, or ask the user for a configuration, if you add it I would thank you very much, thank you for your time

**Comment by Yisus7u7** [comment]
Can you give me an example?

**Comment by amm834** [comment]
`depnds` key of value array `["bash","php"]` automatically install necessary dependencies during installation via `apt (or) dpkg` if they are not installed.
```sh
{
    "name": "lamp",
    "version": "1.1.0",
    "homepage": "http://github.com/amm834/meow",
    "maintainer": "@amm834",
    "description": " 🐘👀 - lamp is a web servers manager ✨",
    "arch":"i686",
    "depends": ["bash","php"], // see this line
    "files" : {
        "lamp":"bin/lamp"
    }
}
```

**Comment by Yisus7u7** [comment]
Ahh, I know that, but what I mean is that I run a script with commands during installation

**Comment by amm834** [comment]
They will install when you install package.

**Comment by Yisus7u7** [comment]
Hmm ok

**Comment by agnostic-apollo** [comment]
You can also run additional commands in [`postinst`](https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html) script.

Note that [`Depends`](https://www.debian.org/doc/debian-policy/ch-binary.html#dependencies) dependencies will not be installed if you install `.deb` file with `dpkg -i` command but they will be installed when its installed with `apt`or `pkg`.
