### ISSUE TITLE
[Feature Request] Support custom multiple archs, please.

### ISSUE THREAD

**Issue by amm834** [termux/termux-create-package#28]
Binary files in `binary-all` of `apt-mirror` can't work for all architectures, so , please support custom multiple `arch` array not only for one arch (ex: `arch:"aarch64"`).

```sh
{
 "arch":["aarch64","and"]
}
```

**Comment by agnostic-apollo** [comment]
Support will be added when I get time to release next version. For now, disabling the check should be enough. Open the file, like with `nano $PREFIX/bin/termux-create-package` and remove like [`66` and `67`](https://github.com/termux/termux-create-package/blob/289ebc4fef6a8e034610695e0399cd321da524d9/termux-create-package#L66)

**Comment by amm834** [comment]
> Support will be added when I get time to release next version. For now, disabling the check should be enough. Open the file, like with `nano $PREFIX/bin/termux-create-package` and remove line [`66` and `67`](https://github.com/termux/termux-create-package/blob/289ebc4fef6a8e034610695e0399cd321da524d9/termux-create-package#L66)

Sound good but removing the some code is not work.
I wait for the next version of this.

**Comment by xeffyr** [comment]
> Binary files in binary-all of apt-mirror can't work for all architectures

?

Always used to mirror (via `apt-mirror` tool) `binary-all` when Termux has been hosted on Bintray.

DEB file format can support only one architecture: either CPU-specific, e.g. `i686`, or `all`. So if your package runs on all architectures, you need to specify `all`, otherwise specify a CPU-specific architecture.

Reference (Debian package format control fields): https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-architecture

**Comment by amm834** [comment]
> > Binary files in binary-all of apt-mirror can't work for all architectures
> 
> ?
> 
> Always used to mirror (via `apt-mirror` tool) `binary-all` when Termux has been hosted on Bintray.
> 
> DEB file format can support only one architecture: either CPU-specific, e.g. `i686`, or `all`. So if your package runs on all architectures, you need to specify `all`, otherwise specify a CPU-specific architecture.
> 
> Reference (Debian package format control fields): https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-architecture
> 
> > Depending on context and the control file used, the Architecture field can include the following sets of values:
> > 
> > * A unique single word identifying a Debian machine architecture as described in Architecture specification strings.
> > * An architecture wildcard identifying a set of Debian machine architectures, see Architecture wildcards. any matches all Debian machine architectures and is the most frequently used.
> > * all, which indicates an architecture-independent package.
> > * source, which indicates a source package.

Yes, I know it.
When defined with `binary-all`  , `apt` did not download from `dists/termux/extras/binary-all` directory.

**Comment by xeffyr** [comment]
There is something wrong with your apt repository.

**Comment by xeffyr** [comment]
Check this example with binary-all: http://termux.net/dists/stable/main/

**Comment by amm834** [comment]
> Check this example with binary-all: https://termux.net/dists/stable/main/
> 
> https://github.com/its-pointless/its-pointless.github.io/tree/master/files/24/dists/termux also hosts binary-all packages successfully.

It is not work for me.
In my case I host my `deb` files on GitHub.

https://github.com/amm834/meow

When I install the package named `lamp` , `apt` is finding at 

https://amm834.github.io/meow/dists/dists/termux/extras/binary-aarch64/lamp_1.1.1_aarch64.deb 

.

`apt` should find to https://github.com/amm834/meow/tree/main/dists/dists/termux/extras/binary-all.

But it is not working.

Error

```
➜  ~ apt install lamp
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  lamp
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 2064 B of archives.
After this operation, 0 B of additional disk space will be used.
Err:1 https://amm834.github.io/meow/dists termux/extras aarch64 lamp aarch64 1.1.1
  404  Not Found [IP: 185.199.108.153 443]
E: Failed to fetch https://amm834.github.io/meow/dists/dists/termux/extras/binary-aarch64/lamp_1.1.1_aarch64.deb  404  Not Found [IP: 185.199.108.153 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
So, how can I solve this?

**Comment by xeffyr** [comment]
![Screenshot_20210508-123853](https://user-images.githubusercontent.com/25881154/117534498-5f456400-affa-11eb-8d10-40256bbff45d.png)

**Comment by amm834** [comment]
Oh! It work on your device.
Why is it not working on `aarch64`.

**Comment by xeffyr** [comment]
My device is aarch64.

Try
```
apt clean
apt update
apt install lamp
```

**Comment by amm834** [comment]
Thank it is work now.
