### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by Auxilus** [termux/termux-create-package#3]
In source code .Py.  It says "resulting.deb file"
But at start it says .JSON file...?
I am so confused plz help me

**Comment by Wetitpig** [comment]
So this is for binary packages, not source code?

**Comment by Wetitpig** [comment]
@Auxilus The JSON file is kind of an index telling the python script what to do. The script generates a .deb file.

**Comment by fornwall** [comment]
You use a json configuration file to specify how to build a .deb file.

See https://github.com/fornwall/cliclac-termux/ for an example project, and run `termux-create-package --help` for more information!
