### ISSUE TITLE
termux-create-package Does not read images 

### ISSUE THREAD

**Issue by Yisus7u7** [termux/termux-create-package#37]
![Screenshot_20220315-195717](https://user-images.githubusercontent.com/64093255/158496364-c4c79fb3-cc86-4b68-b71f-a9f4b808f69b.png)
![Screenshot_20220315-200040](https://user-images.githubusercontent.com/64093255/158496366-4ce5480f-329d-4aee-9beb-831db736c584.png)
![Screenshot_20220315-200447](https://user-images.githubusercontent.com/64093255/158496558-cf637b39-bbfe-4494-9b3a-8cac42c7ab77.png)

I have everything organized correctly, I already tried other things and I realize that termux-create-package does not read images, when adding a directory with images, the images are not added to the package. 

Please arrange this.

**Comment by Yisus7u7** [comment]
![Screenshot_20220315-201116](https://user-images.githubusercontent.com/64093255/158497107-8c5e0cbf-dc86-44f9-88bc-7057fd4a58ee.png)
![Screenshot_20220315-201026](https://user-images.githubusercontent.com/64093255/158497111-e3ac74bb-404b-472b-8d7d-bfbea77fb80c.png)

I am working on a very simple application to "emulate" apps in a proot container, my application uses a few images and as termux-create-package does not add them, the app does not work.

**Comment by Yisus7u7** [comment]
@agnostic-apollo

**Comment by agnostic-apollo** [comment]
> `source_recurse`
The bool value for whether all files under the source path should be recursively added to the deb if its a directory. By default **files under source directories are not automatically/recursively added to the deb. Each file that needs to be added to the deb must be added separately.** This is useful for cases where the files/build directory contains lots of files but you only want specific files to be added to the deb. You may optionally only add a directory entry and not add any file entries, which would ideally result in an empty directory at the target system if it didn't already exist there.

https://github.com/termux/termux-create-package#source_recurse

https://github.com/termux/termux-create-package/blob/v0.12.0/examples/goodbye-world/manifest-android-termux.yml#L56
