### ISSUE TITLE
Missing libandroid-support on WSL

### ISSUE THREAD

**Issue by 2096779623** [termux/termux-create-package#38]
![image](https://user-images.githubusercontent.com/57583560/161472138-0caeec05-8b56-44de-8851-b361f3b500d4.png)

![image](https://user-images.githubusercontent.com/57583560/161472152-7d14670c-2702-4694-94a0-188aec78d2e9.png)

**Comment by wmcbtech30** [comment]
It doesn't exist because Debian distribution doesn't have such packages
