### ISSUE TITLE
termux-create-package on pip needs to be updated

### ISSUE THREAD

**Issue by 2096779623** [termux/termux-create-package#39]
https://pypi.org/project/termux-create-package

The latest version is 0.12.0, but using pip install can only install 0.7.

**Comment by Grimler91** [comment]
Yes, that would be great, but none of the active maintainers have access to @fornwall's pypi account. 

Probably we would have to rename the package to be able to upload it to pypi.

**Comment by agnostic-apollo** [comment]
Could rename to `termux-create-package-v1`. Maybe for `apt` as well.

**Comment by fornwall** [comment]
I have updated the pypi package to 0.12.0 now!

Let me know of your pypi accounts and I'll add you as maintainers as well there.

**Comment by agnostic-apollo** [comment]
Thanks. Mine's https://pypi.org/user/agnostic-apollo/

**Comment by fornwall** [comment]
@agnostic-apollo I've sent you an invite to both `termux-create-package` and `termux-apt-repo` - you need to accept that to be added as an owner.

I think we should (and need) transition to a pypi organisation, to have one place to manage members. A common termux account on pypi will not work after 2FA goes live shortly: https://blog.pypi.org/posts/2023-05-25-securing-pypi-with-2fa/

**Comment by agnostic-apollo** [comment]
Thanks, have accepted, also added our termux.devs account.

All new accounts already require 2FA. But creating an org account might be a good idea. Although security depends on google vs migadu as well.

Have sent you an invite for the fornwall@termux.dev migadu email.

**Comment by Grimler91** [comment]
> But creating an org account might be a good idea. 

I have requested one. Seems it needs to be reviewed by a human to be approved.

**Comment by fornwall** [comment]
As we'll have a pypi organisation account soon, we won't have a dedicated `termuxdevs` pypi user account (which won't work with 2FA anyway), so I've removed that user (added grimler directly instead).

> Have sent you an invite for the [fornwall@termux.dev](mailto:fornwall@termux.dev) migadu email.

Thanks!

**Comment by agnostic-apollo** [comment]
Okay. Welcome.
