### ISSUE TITLE
You cannot perform the script in Cygwin

### ISSUE THREAD

**Issue by SUFandom** [termux/termux-create-package#41]
The `ruamel.yaml` cannot be installed because it needs this Package: `python-dev`

![Capture](https://user-images.githubusercontent.com/70519093/188024773-f4aae537-01fc-4956-bf3f-c16a91a04cbc.PNG)

Which is not Present Under Cygwin Repository Library.

![Capture1](https://user-images.githubusercontent.com/70519093/188024753-7e8f3584-193e-4ae4-a89e-c77d384ff553.PNG)

So yeah. Not Really Much like a bug, but more of compatibility issues

But idk if this can still run, cuz there is JSON, but i think the ruamel.yaml is important

**Comment by agnostic-apollo** [comment]
https://cygwin.com/cgi-bin2/package-grep.cgi?grep=python3-devel&arch=x86_64

https://stackoverflow.com/questions/21843714/cygwin-gcc-issue-cannot-find-python-h
