### ISSUE TITLE
Accessing custom package.

### ISSUE THREAD

**Issue by Auxilus** [termux/termux-create-package#5]
I've created my own package by putting up JSON file and using apt install ./
But if I try to execute it using my package name then it shows no command found ( package is successfully installed)
Please help me with the issue..

**Comment by cocodevienne** [comment]
Check out my package here: http://github.com/cocodevienne/cliclac
@fornwall had to help me a little but it works!:) Just clone the repo and execute the build.sh bash script and you will have built the cliclac package. Try to follow the same directory structure for your script or program! :D @auxilus

**Comment by Auxilus** [comment]
I'll give it a try..
Thanks

**Comment by cocodevienne** [comment]
P.S.: Make the main program executable by running: chmod +x <script> and the build env for my package is designed to be run on Termux itself. @auxilus

**Comment by Auxilus** [comment]
@cocodevienne  I used `termux-create-package script.json` ...
It seems much easier..

**Comment by cocodevienne** [comment]
You should use a build.sh like I have. @auxilus

**Comment by Auxilus** [comment]
I'll try ...Is there any good tutorial for it?
Or can you teach me ??

**Comment by cocodevienne** [comment]
It's very simple really!:) Just have a look at the repo I sent you. :) I've kept the layout of the package veery simple. If you try to follow the same layout then you'll be just fine. If you have any questions you can always ask me and there are no dumb questions! If you want to look at the build.sh then just look inside the "source" folder. Here's the link again: http://github.com/cocodevienne/cliclac @Auxilus

**Comment by cocodevienne** [comment]
Sorry, http://github.com/cocodevienne/cliclac-termux. @Auxilus 
Got my links mixed up. ;)

**Comment by cocodevienne** [comment]
The link to the repo is the link I just commented! Inside it, is everything you need to know. @Auxilus 
Hope this helps.

**Comment by Auxilus** [comment]
@cocodevienne Thanks mate appreciated...

**Comment by cocodevienne** [comment]
No probs dude. @Auxilus
Everything clear?

**Comment by Auxilus** [comment]
Yeah...It is same what I do..But you created a .Ah with them combined..
Got it thanks..
I'll see if I can contribute to your repo..
Thanks again..

**Comment by cocodevienne** [comment]
Okay, glad I could help and clear up a few confusing points. Yes, if you have any ideas for improvement, please do, by all means!! :) @Auxilus
